repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
        files: ^backend/
        args: [--line-length=88]

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        files: ^backend/
        additional_dependencies: [flake8-docstrings]
        args: [--max-line-length=105]

-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        files: ^backend/
        args: ["--profile", "black", "--multi-line-output", "3"]
