FROM python:3.10

WORKDIR /workspace/fastapi-server

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y netcat-openbsd
ENV PYTHONPATH=/workspace/fastapi-server
